config/routes.rb
Rails.application.routes.draw do
  root 'cars#home'
  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  validates :car_make, presence: true, length: { maximum: 30 }
  validates :car_model, presence: true, length: { maximum: 50 }
  validates :car_rating, presence: true, :inclusion => 1..10
  validates :caption, presence: true, length: { maximum: 400 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def home
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.create(car_params)
    if @car.invalid?
      flash[:error] = 'COULD NOT SAVE - the data you entered is invalid.'
    end
    redirect_to root_path
  end

  private

  def car_params
    params.require(:car).permit(:car_make, :car_model, :car_rating, :caption)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/cars/home.html.erb
<div class="home_pic">
</div>

<% @cars.each do |post| %>
  <div class='car-box'>
    Car Make: <%= post.car_make %>
    <br />
    Car Model: <%= post.car_model %>
    <br />
    Rating: <%= post.car_rating %> out of 10
    <br />
    Caption: <%= post.caption %>
  </div>
<% end %>
<br class="clear" />
<br />
<br />
<br />
<br />

app/views/cars/new.html.erb
<div class="form-box">
  <h1>Enter Your Car Details</h1>
  <%= simple_form_for @car do |f| %>
    <%= f.input :car_make, placeholder: 'Lamborghini' %>
    <%= f.input :car_model, placeholder: 'Centenario'%>
    <%= f.input :car_rating,label: 'Rating (Between 1 and 10)', placeholder: '9' %>
    <%= f.input :caption, placeholder: 'I love this car!' %>
    <%= f.submit 'Submit Car', class: 'btn btn-danger float-right' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Car Forums</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        <div class="logo">
          <br />
          <%= link_to 'Car Forums', root_path %>
        </div>
      </div>
      <div class="col-4 slogan">
        <br />
        Find all your car needs right here!
      </div>
      <div class="col-5">
        <br />
        <%= link_to 'Contribute', new_car_path %>
        -
        <%= link_to 'Code for forums' %>
      </div>
    </header>

    <% if flash[:error].present? %>
      <div class="col-10 offset-1 alert alert-danger">
        <%= flash[:error] %>
      </div>
    <% end %>

    <br class="clear" />


    <%= yield %>
  </body>
</html>